### ISSUE TITLE
Feature request: Extending affuse to support more than 999 disk image segments

### ISSUE THREAD

**Issue by gordan-bobic** [sshock/AFFLIBv3#20]
What would it take to modify affuse to support more than 999 disk image segments? I had a look at the code in affuse.c, but it doesn't look like the code I am looking for is there. Can you please point me at the code file that I would need to modify, along with any pointers about what else might break if I were to naively just extend the file name format from a 3 digit suffix to more?

**Comment by sshock** [comment]
Hi gordan.  From what I remember, a split AFF image is known as an AFD, and is stored as a folder named "<name>.afd" with files inside it for each segment named file_000.aff, file_001.aff, etc.

I believe what you are looking for is the aff_filename() function in lib/vnode_afd.cpp, which does this:

`snprintf(buf,buflen,"%s/file_%03d.aff",afd->fname,num);`

But we shouldn't naively change that to %04d or something, or else it will break existing AFD images (e.g., by looking for file_0000.aff instead of file_000.aff).  We don't want to do that.

Have you already tried a split AFF with more than 1000 segments?  Because if I understand printf correctly, formatting a 4-digit number with %03d won't cut anything off, so after file_999.aff you'll get file_1000.aff.

What I'm getting at is, I think this should probably already be working.  But anyway, give it a try and let me know what you find out.

**Comment by jdossett** [comment]
Hi,
I think the problem is not necessarily related to that line.  I am using affuse to try to mount split (non-aff) images.  so image.0001 ... image.1024 for example.  When I try to mount this split image I get an error:

```bash
$ sudo affuse split-ntfs.0001 /tmp/test
Can't open image file: Invalid argument
```
If I try to mount a set of split files with more than 1000 segments that go img.001... img.2048, The resulting raw image is corrupt.

It would be most useful if we could mount segmented images with a 4 character segmentation extension or if we could correct the ordering when trying to mount more than 999 segments.
