### ISSUE TITLE
AFF convert errors & questions

### ISSUE THREAD

**Issue by rlskoeser** [sshock/AFFLIBv3#3]
I need to write a script to convert a bunch of AFF files to E01.  From the readme, it sounds like this library should include a tool for that, but when I go to the actual documentation I can't figure out which tool is supposed do that conversion.  

I was able to get afflib compiled, and the affinfo seems to recognize the AFF files and reports back information that looks reasonable, but when I try to run affconvert to convert from aff to raw, I get this error on every one that I have tried:

> affconvert: af_update_seg: Operation not supported

I can get details on what application was used to create the AFFs if that would help.

Any information or advice you can provide would be appreciated.

**Comment by sshock** [comment]
Hi riskoeser.  Are you using the -r option?  E.g., `./affconvert -r test.aff`

**Comment by rlskoeser** [comment]
@sshock Thank you, that was it!

For two of the three files I was testing with, I now get output like this:
```
convert /tmp/1199_disk3.aff --> /tmp/1199_disk3.raw
Converting page 0 of 0
bytes converted: 1474560
Conversion finished.
```
and the resulting raw files are recognizable as disk images.  The other one is generating empty output, but I'm inclined to think it's an issue with this particular file.

I did look at the man page, but it was not apparent that I needed to use the `-r` flag, since the wording says "force" raw output.  Perhaps it would be worth adding an example with this syntax to the man page?  I'm not very familiar with man page format, but if you want me to take a stab at it I'd be willing to contribute an example for the affconvert man page in a pull request. 

On the EnCase or "E01" format question - does afflib provide any utilities for converting directly to E01 (as seems to be suggested by the mention in the readme), or is the recommended path to use affconvert to go from aff to raw, and then use an E01 specific tool like  libewf to convert from raw to E01?

Thanks so much for your help!

**Comment by sshock** [comment]
Yes, please submit a pull request to fix the man page.  I agree that the use of the word "force" makes it sound like something special instead of normal operation, and the lack of an example going this direction doesn't help.

BTW, if you look inside affconvert.cpp, you will find like 5 examples in usage(); these were commented out when the man page was added.  I can't vouch for the accuracy of all of them, but I think they are probably correct except that they should say .raw instead of .iso (although .iso may work too).  Feel free to include some or all of these in the man page if you can verify their correctness.

afflib doesn't provide any way to convert to E01.  Please remove that line from the README as part of your pull request.  You'll need to convert to raw and then use libewf (ewf-tools) to convert from raw to E01.  I believe Simson was in the process of adding support for libewf to afflib at one time, but didn't get very far.

I only know of one tool that can convert directly from AFF to E01: AccessData's FTK Imager.  You can find it here (it is a free download): http://accessdata.com/product-download  Note that there are also command-line versions available for download, which could be more useful for batch conversions.

**Comment by rlskoeser** [comment]
@sshock thanks so much for the clarification.  I'll try to get a pull request together soon to improve the readme and man page.

Thanks also for the suggestion to look at FTK Imager - I think that's one of the tools our digital curators have been using, but I was not aware there were command-line versions, so that is definitely worth a look!

**Comment by sshock** [comment]
Thank you for the pull request.
