### ISSUE TITLE
Switch from lzma to xz

### ISSUE THREAD

**Issue by kwizart** [sshock/AFFLIBv3#36]
lzma is un-maintained and replaced with xz. Is there any issue to move to (system) xz instead of using the bundled lzma in afflib ?

**Comment by sshock** [comment]
Since afflib is just in maintenance mode, I don't want to make any big changes, especially not if it affects the file format.

But if you just mean updating the lzma code in there by replacing it with the current lzma code from xz utils, and we make sure to stick with lzma not lzma2 so we don't break backward or forward compatibility, and enough testing is performed to verify that, then I would be open to that.
